CREATE TABLE IF NOT EXISTS t_llm_trace_run (
    id BIGINT NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    trace_name VARCHAR(128) NOT NULL,
    entry_method VARCHAR(256) NOT NULL,
    conversation_id VARCHAR(64) DEFAULT NULL,
    task_id VARCHAR(64) DEFAULT NULL,
    user_id VARCHAR(64) DEFAULT NULL,
    status VARCHAR(16) NOT NULL,
    error_message VARCHAR(1000) DEFAULT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP DEFAULT NULL,
    duration_ms BIGINT DEFAULT NULL,
    extra_data CLOB DEFAULT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_t_llm_trace_run_trace_id UNIQUE (trace_id)
);

CREATE TABLE IF NOT EXISTS t_llm_trace_node (
    id BIGINT NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    node_id VARCHAR(64) NOT NULL,
    parent_node_id VARCHAR(64) DEFAULT NULL,
    depth INT NOT NULL DEFAULT 0,
    node_type VARCHAR(32) NOT NULL,
    node_name VARCHAR(128) NOT NULL,
    class_name VARCHAR(256) NOT NULL,
    method_name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    error_message VARCHAR(1000) DEFAULT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP DEFAULT NULL,
    duration_ms BIGINT DEFAULT NULL,
    extra_data CLOB DEFAULT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_t_llm_trace_node_trace_node UNIQUE (trace_id, node_id)
);
